#!/bin/ash
set -e

readonly PID_FILE="/run/opendkim/opendkim.pid"
readonly SOCK_FILE="inet:$APP_PORT"
readonly CONF_FILE="/etc/opendkim/opendkim.conf"

[[ -e "$PID_FILE" ]] && rm -v "$PID_FILE"

# -f: stay in foreground
# -l: log to syslog
# -W: log sign/verify decision logic
# -p: socketfile
# -P: pidfile
# -x: configfile
exec /usr/sbin/opendkim -flW -p "$SOCK_FILE" -P "$PID_FILE" -x "$CONF_FILE"

# vim: set ft=bash ts=2 sts=2 expandtab:

